exmail/web/router.ex
defmodule Exmail.Router do
  use Exmail.Web, :router

  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    # plug :protect_from_forgery
    # plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json", "image", "html"]  # XXX: Add image accepts?
  end

  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated, handler: Exmail.ErrorController
    plug Exmail.Plug.CurrentUser
  end

  scope "/", Exmail do
    pipe_through [:api]
  end

  scope "/", Exmail do
    pipe_through [:browser, :browser_auth]

    get     "/", PageController, :index
    delete  "/logout", AuthController, :logout
    get     "/credentials", AuthController, :credentials
    get     "/signup", SignupController, :new
  end

  scope "/auth", Exmail do
    pipe_through [:browser, :browser_auth]

    get     "/:identity", AuthController, :login
    get     "/:identity/callback", AuthController, :callback
    post    "/:identity/callback", AuthController, :callback
  end

  scope "/", Exmail do
    pipe_through [:browser, :browser_auth, :login_required]
  end

  scope "/campaigns", Exmail do
    pipe_through [:browser, :browser_auth, :login_required]

    get     "/", CampaignController, :index
    post    "/distribute", CampaignController, :distribute
    get     "/distribute", CampaignController, :distribute
    put     "/distribute", CampaignController, :distribute
    delete  "/cancel_email", CampaignController, :cancel_email
  end

  scope "/templates", Exmail do
    pipe_through [:browser, :browser_auth, :login_required]

    post    "/import", TemplateController, :import
    post    "/upload", TemplateController, :upload

    resources "/", TemplateController
  end

  scope "/audiences", Exmail do
    pipe_through [:browser, :browser_auth, :login_required]

    get     "/:audience_id/subscribers/new", SubscriberController, :new
    get     "/:audience_id/subscribers/import", SubscriberController, :import
    post    "/:audience_id/subscribers/import", SubscriberController, :import

    get     "/:audience_id/subscribers/sync", SubscriberController, :sync
    post    "/:audience_id/subscribers/sync", SubscriberController, :sync

    delete  "/:audience_id/subscribers/:subscriber_id", SubscriberController, :delete_relation
    get     "/:audience_id/subscribers/:subscriber_id", SubscriberController, :show
    get     "/:audience_id/subscribers/:subscriber_id/activity", SubscriberController, :show_activity
    get     "/:audience_id/subscribers/:subscriber_id/note", SubscriberController, :show_note

    get     "/:audience_id/subscribers", SubscriberController, :index
    post    "/:audience_id/subscribers", SubscriberController, :create
    delete  "/:audience_id/subscribers", SubscriberController, :delete_relation

    resources "/", AudienceController
  end

  scope "/reports", Exmail do
    pipe_through [:browser, :browser_auth, :login_required]

    get     "/:report_id/overview", ReportController, :overview
    get     "/:report_id/view-email", ReportController, :view_email
    get     "/:report_id/links", ReportController, :links
    get     "/:report_id/activity/sent", ReportController, :activity_sent
    get     "/:report_id/activity/open", ReportController, :activity_open
    get     "/:report_id/activity/open/:audience_id/:subscriber_id", ReportController, :activity_open_subscriber
    get     "/:report_id/activity/click", ReportController, :activity_click
    get     "/:report_id/activity/click/:audience_id/:subscriber_id", ReportController, :activity_click_subscriber
    get     "/:report_id/activity/bounce", ReportController, :activity_bounce

    resources "/", ReportController, only: [:index]
  end

  #scope "/audiences", Exmail do
  #  pipe_through [:browser, :browser_auth]

  #  get "/", AudienceController, :index
  #  get "/new", AudienceController, :new
  #end

  # TODO: These endpoints have to port to Golang system or OpenResty(Redis) system someday.
  scope "/api", Exmail.Api, as: "api" do
    pipe_through [:api]

    get     "/track/:campaign/:email/o", TrackController, :open
    get     "/track/:campaign/:email/hc", TrackController, :html_click
    get     "/track/:campaign/:email/tc", TrackController, :text_click
  end

  scope "/-", Exmail.Api, as: "shorten" do
    pipe_through [:api]

    get     "/:campaign/:email/o", TrackController, :open
    get     "/:campaign/:email/hc", TrackController, :html_click
    get     "/:campaign/:email/tc", TrackController, :text_click
  end

  # Allows you to view all delivered emails.
  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end


end

exmail/web/views/layout_view.ex
defmodule Exmail.LayoutView do
  use Exmail.Web, :view
end

exmail/web/templates/layout/_audience_menu.html.eex
<%
active_index   = current_page? @conn, "subscriber.index:#{@audience.id}"
active_subnew  = current_page? @conn, "subscriber.new:#{@audience.id}"
active_subshow = if assigns[:subscriber], do: current_page?(@conn, "subscriber.show:#{@audience.id}:#{@subscriber.subscriber_id}")
%>

<div class='middle'>
  <ul class="nav nav-tabs">

    <li role='presentation' class="disabled">
      <a class="disabled" href="#"><%= gettext "Stats" %></a>
    </li>

    <li role='presentation' class='dropdown <%= if active_index || active_subshow, do: "active" %>'>
      <a href='<%= subscriber_path @conn, :index, @audience %>'><%= gettext "Manage subscribers" %></a>
    </li>

    <li role='presentation' class='dropdown <%= if active_subnew, do: "active" %>'>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        <%= gettext "Add subscribers" %> <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li class='<%= if active_subnew, do: "active" %>'>
          <a href='<%= subscriber_path @conn, :new, @audience %>'>
            <%= gettext "Add subscriber" %>
          </a>
        </li>
        <li>
          <a href='<%= subscriber_path @conn, :import, @audience %>'>
            <%= gettext "Import subscribers" %>
          </a>
        </li>
        <li>
          <a href='<%= subscriber_path @conn, :sync, @audience %>'>
            <%= gettext "Synchronize subscribers" %>
          </a>
        </li>
      </ul>
    </li>

    <li role='presentation' class='disabled'>
      <a class='disabled' href="#"><%= gettext "Signup form" %></a>
    </li>

    <li role="presentation" class="dropdown disabled">
      <a href="#" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        Settings <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li>
          <a href="#">List name and details</a>
        </li>
        <li>
          <a href="#">Another action</a>
        </li>
        <li>
          <a href="#">Something else here</a>
        </li>
        <li role="separator" class="divider"></li>
        <li>
          <a href="#">Separated link</a>
        </li>
      </ul>
    </li>
  </ul>
</div>

exmail/web/templates/layout/_flash_errors.html.eex
<%= if @form.errors != [] do %>
  <div class="alert alert-danger">
    <p><%= gettext "Oops, something went wrong! Please check the errors below:" %></p>
    <ul>
      <%= for {attr, message} <- @form.errors do %>
        <li><%= translate_default humanize(attr) %> <%= translate_error message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

exmail/web/templates/layout/_footer.html.eex
<footer class="padding">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <a href="/" title="<%#= sitemeta @conn.private[:subdomain], :title %>">
          <%= if false do %>
            <img src='<%= static_path @conn, "/images/icons/f-logo.png" %>' alt="Add alt tag">
          <% end %>
        </a>
        <p>Something </p>
        <small>&copy; Copyright 2014-<%= Timex.now.year %> <%#= sitemeta @conn.private[:subdomain], :title %>. All rights reserved.</small>
        <hr class="mini central light-grey-dk">
      </div>
    </div>
  </div>

  <div class="container-fluid text-left">
    <div class="clearfix">
      <%#= render_with "_footer-inner.html", assigns %>
    </div>
  </div>
</footer>

exmail/web/templates/layout/_header.html.eex
<header id="topbar" class="navbar navbar-default navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only"><%= gettext "Navigation" %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a style="font-size: 14px;" class="navbar-brand" rel="home" href="/" >
        <strong><%#= sitemeta :host %></strong>
      </a>
    </div>

    <nav class="navbar-collapse bs-navbar-collapse collapse" role="navigation" style="height: 1px;">
      <ul itemscope="itemscope" itemtype="http://www.schema.org/SiteNavigationElement" class="nav navbar-nav">
        <li itemprop="name"><a itemprop="url" href='<%= campaign_path @conn, :index %>'>
            <span class="glyphicon glyphicon-send"></span> <%= gettext "Campaigns" %>
        </a></li>
        <li itemprop="name"><a itemprop="url" href='<%= template_path @conn, :index %>'>
            <span class="glyphicon glyphicon-th-list"></span> <%= gettext "Templates" %>
        </a></li>
        <li itemprop="name"><a itemprop="url" href='<%= audience_path @conn, :index %>'>
            <span class="glyphicon glyphicon-zoom-in"></span> <%= gettext "Audiences" %>
        </a></li>
        <li itemprop="name"><a itemprop="url" href='<%= report_path @conn, :index %>'>
            <span class='glyphicon glyphicon-indent-right'></span> <%= gettext "Reports" %>
        </a></li>
      </ul>

      <ul itemscope="itemscope" itemtype="http://www.schema.org/SiteNavigationElement" class="nav navbar-nav navbar-right">
        <%= if Guardian.Plug.current_resource(@conn) do %>
          <li itemprop="name" >
            <%= link to: auth_path(@conn, :logout), method: :delete, class: "btn btn-link", itemprop: "url" do %>
              <span class='glyphicon glyphicon-remove-sign'></span> <%= gettext "Sign Out" %>
            <% end %>
          </li>
        <% else %>
          <li itemprop="name">
            <a itemprop="url" href='<%= auth_path @conn, :login, "identiry" %>'>
              <span class='glyphicon glyphicon-ok-sign'></span> <%= gettext "Sign In" %>
            </a>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>

  <%= if get_flash(@conn, :info) do %>
    <div style='margin-bottom: 0;' class="alert alert-info alert-dismissible text-center button-boder-line" role="alert">
      <button type="button" class="close text-center" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= raw get_flash(@conn, :info) %>
    </div>
  <% end %>
  <%= if get_flash(@conn, :warn) do %>
    <div style='margin-bottom: 0;' class="alert alert-warning alert-dismissible text-center button-boder-line" role="alert">
      <button type="button" class="close text-center" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= raw get_flash(@conn, :warn) %>
    </div>
  <% end %>
  <%= if get_flash(@conn, :error) do %>
    <div style='margin-bottom: 0;' class="alert alert-danger alert-dismissible text-center button-boder-line" role="alert">
      <button type="button" class="close text-center" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= raw get_flash(@conn, :error) %>
    </div>
  <% end %>

</header>

exmail/web/templates/layout/_overview_menu.html.eex
<%
active_sent   = current_page? @conn, "report.activity_sent:#{@report.id}"
active_open   = current_page? @conn, "report.activity_open:#{@report.id}"
active_click  = current_page? @conn, "report.activity_click:#{@report.id}"
active_bounce = current_page? @conn, "report.activity_bounce:#{@report.id}"
%>

<div class='middle'>
  <ul class="nav nav-tabs">

    <li role='presentation' class='<%= if current_page?(@conn, "report.overview:#{@report.id}"), do: "active" %>'>
      <a href='<%= report_path @conn, :overview, @report %>'><%= gettext "Overview" %></a>
    </li>

    <li role='presentation' class='dropdown <%= if active_sent or active_open or active_click or active_bounce, do: "active" %>'>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        <%= gettext "Activity" %> <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li class='<%= if active_sent, do: "active" %>'>
          <a href='<%= report_path @conn, :activity_sent, @report %>'>
            <%= gettext "Sent to" %>
          </a>
        </li>
        <li class='<%= if active_open, do: "active" %>'>
          <a href='<%= report_path @conn, :activity_open, @report %>'>
            <%= gettext "Opened" %>
          </a>
        </li>
        <li class='<%= if active_click, do: "active" %>'>
          <a href='<%= report_path @conn, :activity_click, @report %>'>
            <%= gettext "Cliked" %>
          </a>
        </li>
        <li class='<%= if active_bounce, do: "active" %>'>
          <a href='<%= report_path @conn, :activity_bounce, @report %>'>
            <%= gettext "Bounced" %>
          </a>
        </li>
      </ul>
    </li>

    <li role='presentation' class='<%= if current_page?(@conn, "report.links:#{@report.id}"), do: "active" %>'>
      <a href="<%= report_path @conn, :links, @report %>"><%= gettext "Links" %></a>
    </li>

    <li role='presentation' class='disabled'>
      <a disabled href="#"><%= gettext "Social" %></a>
    </li>

    <li role='presentation' class='disabled'>
      <a disabled href="#"><%= gettext "E-commerce" %></a>
    </li>

    <li role='presentation' class='disabled'>
      <a disabled href="#"><%= gettext "Conversations" %></a>
    </li>

    <li role='presentation' class='disabled'>
      <a disabled href="#"><%= gettext "Analytics360" %></a>
    </li>

  </ul>
</div>

exmail/web/templates/layout/_report_menu.html.eex
<%
#active_subnew = current_page? @conn, "subscriber.new:#{@audience.id}"
%>

<div class='middle'>
  <ul class="nav nav-tabs">

    <li role='presentation'>
      <a href="#"><%= gettext "Campaigns" %></a>
    </li>

    <li role='presentation'>
      <a href='#'><%= gettext "Comparative" %></a>
    </li>

    <li role='presentation' class='disabled'>
      <a disabled href="#"><%= gettext "Automation" %></a>
    </li>

  </ul>
</div>

exmail/web/templates/layout/_report_switcher.html.eex
<div class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
    <%= gettext "Switch report" %> <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" aria-labelledby="dLabel">
    <%= for r <- @switchers do %>
      <li class='two-columns'>
        <a href="<%= report_path @conn, :overview, r %>" >
          <span><%= r.campaign.name %></span>
          <span><%= view_time(r.inserted_at) %></span>
        </a>
      </li>
    <% end %>
    <li role="separator" class="divider"></li>
    <li><a href="<%= report_path @conn, :index %>"><%= gettext "View All" %></a></li>
  </ul>
</div>

exmail/web/templates/layout/_subscriber_bouncedetail.html.eex
<div class="modal bounce-messages" tabindex="-1" role="dialog" aria-labelledby="BounceMessage">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

        <div class="table-responsive">
          <table class="table table-hover table-condensed">
            <thead>
              <tr>
                <th class="ctext"></th>
                <th class="ltext">Reason Name</th>
                <th class="ctext">Hard Bounce</th>
                <th class="ctext">Description</th>
              </tr>
            </thead>
            <tbody>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-user-times" title="By Address"></i></td>
                <td class="ltext"><strong><span>Host Unknown</span></strong></td>
                <td><strong>Yes</strong></td>
                <td class="ltext">Destination host name does not exist</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-user-times" title="By Address"></i></td>
                <td class="ltext"><strong><span>User Unknown</span></strong></td>
                <td><strong>Yes</strong></td>
                <td class="ltext">Recipient's address does not exist</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-user-times" title="By Address"></i></td>
                <td class="ltext"><strong><span>Filtered</span></strong></td>
                <td>No</td>
                <td class="ltext">Rejected after DATA command</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-user-times" title="By Address"></i></td>
                <td class="ltext"><strong><span>Has Moved</span></strong></td>
                <td><strong>Yes</strong></td>
                <td class="ltext">Destination mail addrees has moved</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-user-times" title="By Address"></i></td>
                <td class="ltext"><strong><span>Rejected</span></strong></td>
                <td>No</td>
                <td class="ltext">Rejected due to envelope from address</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-user-times" title="By Address"></i></td>
                <td class="ltext"><strong><span>Mailbox Full</span></strong></td>
                <td>No</td>
                <td class="ltext">Recipient's mailbox is full</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-user-times" title="By Address"></i></td>
                <td class="ltext"><strong><span>Suspend</span></strong></td>
                <td>No</td>
                <td class="ltext">Recipient's account is suspended</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-user-times" title="By Address"></i></td>
                <td class="ltext"><strong><span>Vacation</span></strong></td>
                <td>No</td>
                <td class="ltext">Auto replied message (recipient is away)</td>
              </tr>

              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-file-text-o" title="By Content"></i></td>
                <td class="ltext"><strong><span>Content Error</span></strong></td>
                <td>No</td>
                <td class="ltext">Email body or header is invalid format</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-file-text-o" title="By Content"></i></td>
                <td class="ltext"><strong><span>Exceed Limit</span></strong></td>
                <td>No</td>
                <td class="ltext">Message size exceeded the limit(5.2.3)</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-file-text-o" title="By Content"></i></td>
                <td class="ltext"><strong><span>Feedback</span></strong></td>
                <td>No</td>
                <td class="ltext">Bounced for a complaint of the message(FBL)</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-file-text-o" title="By Content"></i></td>
                <td class="ltext"><strong><span>Mesg Too Big</span></strong></td>
                <td>No</td>
                <td class="ltext">Message size is too big(5.3.4)</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-file-text-o" title="By Content"></i></td>
                <td class="ltext"><strong><span>Security Error</span></strong></td>
                <td>No</td>
                <td class="ltext">Virus detected or authentication error</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-file-text-o" title="By Content"></i></td>
                <td class="ltext"><strong><span>Spam Detected</span></strong></td>
                <td>No</td>
                <td class="ltext">Detected a message as spam</td>
              </tr>

              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-server" title="By Server"></i></td>
                <td class="ltext"><strong><span>Blocked</span></strong></td>
                <td>No</td>
                <td class="ltext">Blocked due to client IP address or hostname</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-server" title="By Server"></i></td>
                <td class="ltext"><strong><span>Expired</span></strong></td>
                <td>No</td>
                <td class="ltext">Delivery time expired</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-server" title="By Server"></i></td>
                <td class="ltext"><strong><span>Mailer Error</span></strong></td>
                <td>No</td>
                <td class="ltext">Mailer program error on remote host</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-server" title="By Server"></i></td>
                <td class="ltext"><strong><span>Network Error</span></strong></td>
                <td>No</td>
                <td class="ltext">Network error: DNS or routing</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-server" title="By Server"></i></td>
                <td class="ltext"><strong><span>No Relaying</span></strong></td>
                <td>No</td>
                <td class="ltext">Relay access denied</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-server" title="By Server"></i></td>
                <td class="ltext"><strong><span>Not Accept</span></strong></td>
                <td>No</td>
                <td class="ltext">Destinaion does not accept any message</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-server" title="By Server"></i></td>
                <td class="ltext"><strong><span>System Error</span></strong></td>
                <td>No</td>
                <td class="ltext">Some error on the destination host</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-server" title="By Server"></i></td>
                <td class="ltext"><strong><span>System Full</span></strong></td>
                <td>No</td>
                <td class="ltext">Disk full on the destination host</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-server" title="By Server"></i></td>
                <td class="ltext"><strong><span>Too Many Conn</span></strong></td>
                <td>No</td>
                <td class="ltext">Connection rate limit exceeded</td>
              </tr>

              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-question-circle" title="Others"></i></td>
                <td class="ltext"><strong><span>Delivered</span></strong></td>
                <td>No</td>
                <td class="ltext">Successfully delivered</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-question-circle" title="Others"></i></td>
                <td class="ltext"><strong><span>Syntax Error</span></strong></td>
                <td>No</td>
                <td class="ltext">syntax error in SMTP</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-question-circle" title="Others"></i></td>
                <td class="ltext"><strong><span>On Hold</span></strong></td>
                <td>No</td>
                <td class="ltext">Deciding the bounce reason is on hold</td>
              </tr>
              <tr class="row-as-a-link">
                <td class="ltext"><i class="fa fa-question-circle" title="Others"></i></td>
                <td class="ltext"><strong><span>Undefined</span></strong></td>
                <td>No</td>
                <td class="ltext">Could not decide an error reason</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

exmail/web/templates/layout/_subscriber_menu.html.eex
<%
active_detail   = current_page?(@conn, "subscriber.show:#{@audience.id}:#{@subscriber.subscriber_id}")
active_activity = current_page?(@conn, "subscriber.show_activity:#{@audience.id}:#{@subscriber.subscriber_id}")
%>

<div class='middle'>
  <ul class="nav nav-tabs">

    <li role='presentation' class="<%= if active_detail, do: "active" %>">
      <a href="<%= subscriber_path @conn, :show, @audience.id, @subscriber.subscriber_id %>#menu-target"><%= gettext "Detail" %></a>
    </li>

    <li role='presentation' class='<%= if active_activity, do: "active" %>'>
      <a href='<%= subscriber_path @conn, :show_activity, @audience.id, @subscriber.subscriber_id %>#menu-target'><%= gettext "Activity" %></a>
    </li>

    <li role='presentation' class='disabled'>
      <a class='disabled' href="#"><%= gettext "Notes" %></a>
    </li>

    <li role='presentation' class='disabled'>
      <a class='disabled' href="#"><%= gettext "Conversations" %></a>
    </li>

    <li role='presentation' class='disabled'>
      <a class='disabled' href="#"><%= gettext "E-commerce" %></a>
    </li>

    <li role='presentation' class='disabled'>
      <a class='disabled' href="#"><%= gettext "Goals" %></a>
    </li>

    <li role='presentation' class='disabled'>
      <a class='disabled' href="#"><%= gettext "Social Profiles" %></a>
    </li>

  </ul>
</div>

exmail/web/templates/layout/_subscriber_profile.html.eex
<div class='profile'>
  <div class="media">
    <div class="media-left">
      <img class="media-object" src="<%= gravatar @subscriber.email %>">
    </div>
    <div class="media-body">
      <nav aria-label="<%= gettext "Move next subscriber" %>">
        <ul class="pager">
          <li><%= gettext "%{current} of %{all}", current: @subscriber.id, all: "Unknown" %></li>
          <li>
            <%= if @pager_prev do %>
              <a href="<%= subscriber_path @conn, :show, @pager_prev.audience_id, @pager_prev.subscriber_id %>">
                &leftarrow;
              </a>
            <% else %>
              <span>&leftarrow;</span>
            <% end %>
          </li>
          <li>
            <%= if @pager_next do %>
              <a href="<%= subscriber_path @conn, :show, @pager_next.audience_id, @pager_next.subscriber_id %>">
                &rightarrow;
              </a>
            <% else %>
              <span>&rightarrow;</span>
            <% end %>
          </li>
        </ul>
      </nav>
      <p><strong><%= @subscriber.email %></strong></p>
      <p><%= @subscriber.first_name %> <%= @subscriber.last_name %></p>
      <p>Not yet, e.g. (Subscribed Jan 23, 2017 11:56 pm)</p>
    </div>
  </div>

  <div class='profile-buttons' id='menu-target'>
    <div class="btn-group">
      <button type="button" class="btn btn-default btn-sm on-off-able" data-loading-text="Changing..." autocomplete="off" data-on="/vip/on" data-off="/vip/off">
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span> <%= gettext "VIP" %>
      </button>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-default btn-sm on-off-able" data-loading-text="Changing..." autocomplete="off" data-on="/unsubscribe/on" data-off="/unsubscribe/off">
        <%= gettext "Unsubscribe" %>
      </button>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-default btn-sm on-off-able" data-loading-text="Changing..." autocomplete="off" data-on="/delete/on" data-off="/delete/off">
        <%= gettext "Delete" %>
      </button>
    </div>
  </div>
</div>