exmail/web/router.ex
defmodule Exmail.Router do
  use Exmail.Web, :router

  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    # plug :protect_from_forgery
    # plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json", "image", "html"]  # XXX: Add image accepts?
  end

  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated, handler: Exmail.ErrorController
    plug Exmail.Plug.CurrentUser
  end

  scope "/", Exmail do
    pipe_through [:api]
  end

  scope "/", Exmail do
    pipe_through [:browser, :browser_auth]

    get     "/", PageController, :index
    delete  "/logout", AuthController, :logout
    get     "/credentials", AuthController, :credentials
    get     "/signup", SignupController, :new
  end

  scope "/auth", Exmail do
    pipe_through [:browser, :browser_auth]

    get     "/:identity", AuthController, :login
    get     "/:identity/callback", AuthController, :callback
    post    "/:identity/callback", AuthController, :callback
  end

  scope "/", Exmail do
    pipe_through [:browser, :browser_auth, :login_required]
  end

  scope "/campaigns", Exmail do
    pipe_through [:browser, :browser_auth, :login_required]

    get     "/", CampaignController, :index
    post    "/distribute", CampaignController, :distribute
    get     "/distribute", CampaignController, :distribute
    put     "/distribute", CampaignController, :distribute
    delete  "/cancel_email", CampaignController, :cancel_email
  end

  scope "/templates", Exmail do
    pipe_through [:browser, :browser_auth, :login_required]

    post    "/import", TemplateController, :import
    post    "/upload", TemplateController, :upload

    resources "/", TemplateController
  end

  scope "/audiences", Exmail do
    pipe_through [:browser, :browser_auth, :login_required]

    get     "/:audience_id/subscribers/new", SubscriberController, :new
    get     "/:audience_id/subscribers/import", SubscriberController, :import
    post    "/:audience_id/subscribers/import", SubscriberController, :import

    get     "/:audience_id/subscribers/sync", SubscriberController, :sync
    post    "/:audience_id/subscribers/sync", SubscriberController, :sync

    delete  "/:audience_id/subscribers/:subscriber_id", SubscriberController, :delete_relation
    get     "/:audience_id/subscribers/:subscriber_id", SubscriberController, :show
    get     "/:audience_id/subscribers/:subscriber_id/activity", SubscriberController, :show_activity
    get     "/:audience_id/subscribers/:subscriber_id/note", SubscriberController, :show_note

    get     "/:audience_id/subscribers", SubscriberController, :index
    post    "/:audience_id/subscribers", SubscriberController, :create
    delete  "/:audience_id/subscribers", SubscriberController, :delete_relation

    resources "/", AudienceController
  end

  scope "/reports", Exmail do
    pipe_through [:browser, :browser_auth, :login_required]

    get     "/:report_id/overview", ReportController, :overview
    get     "/:report_id/view-email", ReportController, :view_email
    get     "/:report_id/links", ReportController, :links
    get     "/:report_id/activity/sent", ReportController, :activity_sent
    get     "/:report_id/activity/open", ReportController, :activity_open
    get     "/:report_id/activity/open/:audience_id/:subscriber_id", ReportController, :activity_open_subscriber
    get     "/:report_id/activity/click", ReportController, :activity_click
    get     "/:report_id/activity/click/:audience_id/:subscriber_id", ReportController, :activity_click_subscriber
    get     "/:report_id/activity/bounce", ReportController, :activity_bounce

    resources "/", ReportController, only: [:index]
  end

  #scope "/audiences", Exmail do
  #  pipe_through [:browser, :browser_auth]

  #  get "/", AudienceController, :index
  #  get "/new", AudienceController, :new
  #end

  # TODO: These endpoints have to port to Golang system or OpenResty(Redis) system someday.
  scope "/api", Exmail.Api, as: "api" do
    pipe_through [:api]

    get     "/track/:campaign/:email/o", TrackController, :open
    get     "/track/:campaign/:email/hc", TrackController, :html_click
    get     "/track/:campaign/:email/tc", TrackController, :text_click
  end

  scope "/-", Exmail.Api, as: "shorten" do
    pipe_through [:api]

    get     "/:campaign/:email/o", TrackController, :open
    get     "/:campaign/:email/hc", TrackController, :html_click
    get     "/:campaign/:email/tc", TrackController, :text_click
  end

  # Allows you to view all delivered emails.
  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end


end

exmail/web/models/campaign/abtesttype.ex
defmodule Exmail.Campaign.ABTesttype do
  use Exmail.Web, :model
  use Arc.Ecto.Schema
  use Exmail.Concerns.Campaign.CampaignType

  alias Exmail.{Campaign, TemplateUploader, AlternativeUploader}

  track_open true
  track_html_click true
  track_text_click true

  schema "abtesttypes" do
    many_to_many :images, Exmail.Image, join_through: "abtesttypes_images",
      on_delete: :delete_all, on_replace: :delete

    belongs_to :campaign, Campaign

    field :from_email, :string
    field :from_name, :string

    field :subject, :string
    field :tpl, TemplateUploader.Type
    field :alt, AlternativeUploader.Type  # Alternative tpl that uses as fallback

    field :schedule, :utc_datetime

    timestamps()
  end

  @attaches ~w(tpl alt)a
  @castable ~w(campaign_id from_email from_name subject schedule)a
  @requires ~w()a

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @castable)
    |> validate_required(@requires)
    |> cast_attachments(params, @attaches)
  end

  @doc """
  The number three(0..2) which tries to testing in abtest.
  """
  def trials(tries \\ 3) do
    Enum.map 1..tries, fn _ -> %__MODULE__{} end
  end

end

exmail/web/models/campaign/regulartype.ex
defmodule Exmail.Campaign.Regulartype do
  use Exmail.Web, :model
  use Arc.Ecto.Schema
  use Exmail.Concerns.Campaign.CampaignType

  alias Exmail.{Campaign, TemplateUploader, AlternativeUploader}

  track_open true
  track_html_click true
  track_text_click true

  schema "regulartypes" do
    many_to_many :images, Exmail.Image, join_through: "regulartypes_images",
      on_delete: :delete_all, on_replace: :delete

    belongs_to :campaign, Campaign

    field :from_email, :string
    field :from_name, :string

    field :subject, :string
    field :tpl, TemplateUploader.Type
    field :alt, AlternativeUploader.Type  # Alternative tpl that uses as fallback

    field :schedule, :utc_datetime

    timestamps()
  end

  @attaches ~w(tpl alt)a
  @castable ~w(campaign_id from_email from_name subject schedule)a
  @requires ~w()a

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @castable)
    |> validate_required(@requires)
    |> cast_attachments(params, @attaches)
  end

end

exmail/web/controllers/campaign_controller.ex
defmodule Exmail.CampaignController do
  use Exmail.Web, :controller

  alias Exmail.{Campaign, Report, Template, Service, ImageUploader, AlternativeUploader, Tasks}
  alias Exmail.CampaignView, as: ViewH
  # alias Exmail.Concerns.CampaignController, as: CtrlH

  require Logger

  plug Exmail.Plug.CurrentUser
  plug ViewH.AssignCampaign when action in [:distribute, :cancel_email]
  plug ViewH.AssignCampaignType when action in [:distribute, :cancel_email]

  @wizard_prefix "distribute_"

  def distribute(%Plug.Conn{assigns: %{campaign: _campaign}} = conn, %{"wizard" => "Sent", "rid" => _rid}, _current_user, _) do
    render conn, "#{@wizard_prefix}sent.html"
  end

  def distribute(%Plug.Conn{assigns: %{campaign: campaign}} = conn, %{"wizard" => "SendMail", "schedule" => schedule}, current_user, _) do
    params   = %{"user_id" => current_user.id, "campaign_id" => campaign.id, "schedule" => schedule}
    campaign = Repo.preload campaign, [:user, audience: [:subscribers]]

    # TODO: Email Validation.

    # do_some_verification

    with {:ok, _reltype} <- Tasks.Sendmail.reserve(campaign, params),
         {:ok, report} <- Repo.insert(Report.changeset(%Report{}, params)) do

        redirect conn, to: campaign_path(conn, :distribute, id: campaign.id, rid: report.id, wizard: "Sent")
    else
      {:error, changeset} ->
        render conn, "#{@wizard_prefix}confirm.html", changeset: changeset
      # {:error, mailerror} ->
        # render conn, "#{@wizard_prefix}confirm.html", mailerror: mailerror
    end
  end

  def distribute(%Plug.Conn{assigns: %{campaign: campaign}} = conn, %{"wizard" => "Confirm"}, _current_user, _) do
    campaign = Repo.preload campaign, audience: [:subscribers]

    conn
    |> render("#{@wizard_prefix}confirm.html", campaign: campaign)
  end

  def distribute(%Plug.Conn{assigns: %{reltype: reltype}} = conn, %{"wizard" => "SaveFallback", "body" => _body} = params, _current_user, _) do
    Service.Tpl.update_stored reltype, params, &AlternativeUploader.store/1  # Fallback
    json conn, %{msg: "ok"}
  end

  def distribute(%Plug.Conn{assigns: %{reltype: reltype}} = conn, %{"wizard" => "SaveDesign", "body" => _body} = params, _current_user, _) do
    Service.Tpl.update_stored reltype, params  # Main
    json conn, %{msg: "ok"}
  end

  def distribute(%Plug.Conn{assigns: %{reltype: reltype}} = conn, %{"wizard" => "SaveFile", "image" => datauri}, current_user, _) do
    params = %{"src" => datauri, "user_id" => current_user.id}

    Repo.transaction(fn ->
      with {:ok, image}    <- Service.Image.create(params),
           {:ok, _reltype} <- Repo.insert(Campaign.image_changeset(reltype, image)) do
        image
      else
        {:error, changeset} -> Repo.rollback changeset
      end
    end)
    |> case do
      {:ok, image} ->
        json conn, %{status: true, message: "ok", url: ImageUploader.develop_url({image.src, image})}

      {:error, changeset} ->
        errors = translate_errors(changeset) |> Enum.join("\n")
        json conn, %{status: false, message: errors}
    end
  end

  def distribute(%Plug.Conn{assigns: %{reltype: _reltype}} = conn, %{"wizard" => "Design"}, _current_user, _) do
    conn
    |> put_layout("wizard_app.html")
    |> render("#{@wizard_prefix}design.html")
  end

  def distribute(%Plug.Conn{assigns: %{campaign: campaign, reltype: reltype}} = conn, %{"wizard" => "PlainText"}, _current_user, _) do
    unless reltype.tpl do
      params = %{"body" => ViewH.default_plain_text()}
      Repo.update Campaign.tpl_changeset(campaign, reltype, params)
    end

    conn
    |> put_layout("wizard_app.html")
    |> render("#{@wizard_prefix}plaintext.html")
  end

  def distribute(%Plug.Conn{assigns: %{campaign: campaign, reltype: reltype}} = conn, %{"wizard" => "SaveTemplate"} = params, _current_user, _) do
    template  = Repo.get_by! Template, id: params["tid"]
    changeset = Campaign.tpl_changeset campaign, reltype, template

    case Repo.update changeset do
      {:ok, reltype} ->
        redirect(conn, to: campaign_path(conn, :distribute, id: campaign.id, relid: reltype.id, wizard: "Design"))

      {:error, changeset} ->
        errors = translate_errors(changeset) |> Enum.join("\n")
        conn
        |> put_flash(:error, gettext("Something went wrongs. %{msgs}", msgs: errors))
        |> redirect(to: campaign_path(conn, :distribute, id: campaign.id, wizard: "Template"))
    end
  end

  def distribute(%Plug.Conn{assigns: %{campaign: _campaign}} = conn, %{"wizard" => "Contents"}, _current_user, _) do
    conn
    |> put_layout("wider_app.html")
    |> render("#{@wizard_prefix}contents.html")
  end

  def distribute(%Plug.Conn{assigns: %{campaign: _campaign}} = conn, %{"wizard" => "Strategy"}, _current_user, _) do
    conn
    |> put_layout("wider_app.html")
    |> render("#{@wizard_prefix}strategy.html")
  end

  def distribute(%Plug.Conn{assigns: %{campaign: _campaign}} = conn, %{"wizard" => "Template"}, current_user, _) do
    templates =
      from(q in Template,
        where: q.user_id == ^(current_user.id),
        preload: :user
      ) |> Repo.all

    seeds =
      from(q in Template, where: q.type == "Seeds")
      |> Repo.all

    conn
    |> put_layout("wider_app.html")
    |> render("#{@wizard_prefix}template.html", templates: templates, seeds: seeds)
  end

  # Save recipient type to database with remeining session data.
  def distribute(conn, %{"wizard" => "SaveSetup", "campaign" => params}, _current_user, _) do
    {campaign, type, audience_id} =
      if present? params["id"] do
        campaign = Campaign |> Campaign.with_types |> Campaign.with_audience |> Repo.get!(params["id"])
        {campaign, campaign.type, campaign.audience.id}
      else
        campaign = Repo.preload %Campaign{}, Campaign.reltypes
        {campaign, ViewH.get_dvalue(conn, "type"), ViewH.get_dvalue(conn, "audience_id")}
      end

    params = Map.merge(params, %{
      "type" => type,
      "user_id" => conn.assigns.current_user.id,
      "audience_id" => audience_id,
    })

    Repo.transaction(fn ->
      with {:ok, campaign}  <- Repo.insert_or_update(Campaign.setup_changeset(campaign, params)),
           {:ok, campaign}  <- Repo.insert_or_update(Campaign.rel_changeset(campaign, params)) do
        campaign
      else
        {:error, changeset} -> Repo.rollback changeset
      end
    end)
    |> case do
      {:ok, %{type: "ABTest"} = campaign} ->
        conn
        |> ViewH.del_dvalue
        |> redirect(to: campaign_path(conn, :distribute, id: campaign.id, wizard: "Contents"))

      {:ok, %{type: "Text"} = campaign} ->
        relid = Campaign.reltype(campaign).id
        conn
        |> ViewH.del_dvalue
        |> redirect(to: campaign_path(conn, :distribute, id: campaign.id, relid: relid, wizard: "PlainText"))

      {:ok, campaign} ->
        relid = Campaign.reltype(campaign).id
        conn
        |> ViewH.del_dvalue
        |> redirect(to: campaign_path(conn, :distribute, id: campaign.id, relid: relid, wizard: "Template"))

      {:error, changeset} ->
        campaign  = ViewH.new_campaign(conn, audience_id)
        changeset = struct(changeset, [data: campaign])
        render conn, "#{@wizard_prefix}setup.html", changeset: changeset, campaign: campaign
    end
  end

  # Save recipient type to session
  def distribute(conn, %{"wizard" => "Setup", "recipient_audience" => ra} = _params, _current_user, _) do
    [recipient, audience_id] = String.split ra, "-"

    # Build changset with campaign type
    campaign  = ViewH.new_campaign conn, audience_id
    changeset = Campaign.changeset campaign

    conn
    |> ViewH.put_dvalue("recipient", recipient)  # TODO: Just to support distribution to entire audiences currently.
    |> ViewH.put_dvalue("audience_id", audience_id)
    |> render("#{@wizard_prefix}setup.html", changeset: changeset, campaign: campaign)
  end

  def distribute(%Plug.Conn{assigns: %{campaign: campaign}} = conn, %{"wizard" => "Setup", "id" => _id} = _params, _current_user, _) do
    changeset = Campaign.changeset(campaign)
    conn
    |> render("#{@wizard_prefix}setup.html", changeset: changeset, campaign: campaign)
  end

  # Save campaign type to session
  def distribute(conn, %{"wizard" => "Recipient", "type" => type} = params, _current_user, _) do
    user = Repo.preload conn.assigns.current_user, audiences: [:subscribers]

    conn
    |> ViewH.put_dvalue("type", type)
    |> render("#{@wizard_prefix}recipient.html", audiences: user.audiences)  # TODO: pagination, using list pagination
  end

  def distribute(conn, _params, _current_user, _) do
    render conn, "#{@wizard_prefix}type.html"
  end

  @doc """
  If system doesn't send email yet, this is gonna cancel send-email.
  """
  def cancel_email(%Plug.Conn{assigns: %{campaign: campaign}} = conn, _params, _current_user, _) do
    case Tasks.Sendmail.cancel(campaign) do
      {:ok, _reltype} ->
        conn
        |> put_flash(:info, gettext("Cancelled send-email successful accomplished."))
        |> redirect(to: campaign_path(conn, :index))

      {:timeover, _error} ->
        conn
        |> put_flash(:error, gettext("Time was up! Emali sent already, it hasn't cancelled."))
        |> redirect(to: campaign_path(conn, :index))

      {:error, error} ->
        Logger.error(inspect error)

        msg = gettext("There's something wrong, please make sure email's data and documentation")
        conn
        |> put_flash(:error, msg)
        |> redirect(to: campaign_path(conn, :index))
    end
  end

  def index(conn, params, _current_user, _) do
    render conn, "index.html", campaigns: Repo.paginate(ViewH.index_list(conn), params)
  end

end

exmail/web/controllers/concerns/campaign_controller.ex
defmodule Exmail.Concerns.CampaignController do
  @moduledoc """
  Must use Exmail.Web, :controller
  """
  use Exmail.Web, :controller
end

exmail/web/templates/campaign/distribute_recipient.html.eex
<div class='resources col-lg-10 col-centered'>

  <h1 class='h2 text-center'>
    <%= gettext "Who are you sending to?" %>
  </h1>

  <div class="middle">
    <%= for ad <- @audiences do %>
      <div class="media">
        <div class="media-body pointer" aria-controls="recipient-radio" aria-expanded="true" data-target="#recipient-radio-<%= ad.id %>" data-toggle="collapse">
          <h3 class="media-heading"><%= translate_default ad.name %></h3>
          <%= if ad.from_email do %>
            <h4><small><%= gettext "Default E-Mail: %{email}", email: ad.from_email %></small></h4>
          <% end %>
          <%= if ad.from_name do %>
            <h4><small><%= gettext "Default Name: %{name}", name: ad.from_name %></small></h4>
          <% end %>
          <small><%= ad.explain || gettext("No explaining yet") %></small>
        </div>
        <div class="media-right vmiddle" aria-controls="recipient-radio" aria-expanded="true" data-target="#recipient-radio-<%= ad.id %>" data-toggle="collapse">
          <button class="btn btn-default" type="button">
            <%= gettext "Select" %>
          </button>
        </div>
      </div>

      <div class="collapse" id="recipient-radio-<%= ad.id %>" aria-expanded="true">
        <label class="radio-inline">
          <input type="radio" name="recipient_audience" id="inlineRadio<%= ad.id %>1" value='<%= "entire-#{ad.id}" %>' checked> <%= gettext "Entire list" %>
        </label>
        <label class="radio-inline">
          <input type="radio" name="recipient_audience" id="inlineRadio<%= ad.id %>2" value='<%= "presegs-#{ad.id}" %>' disabled> <%= gettext "Saved or pre-built segment" %>
        </label>
        <label class="radio-inline">
          <input type="radio" name="recipient_audience" id="inlineRadio<%= ad.id %>3" value='<%= "newseg-#{ad.id}" %>' disabled> <%= gettext "Group or new segment" %>
        </label>
        <label class="radio-inline">
          <%= link gettext("Next　>>"), to: campaign_path(@conn, :distribute, wizard: "Setup"), id: "save-recipient-#{ad.id}", class: "btn btn-primary disabled", method: :post %>
        </label>

        <div class='help-block'>
          <%= gettext "%{total} recipients. Everyone in your list will receive this email.", total: length(ad.subscribers) %>
        </div>

      </div>
    <% end %>

    <%= if length(@audiences) <= 0 do %>
      <h2 class='h4 text-center'>
        <a href='<%= audience_path @conn, :new %>' target='_blank'>
        <%= gettext "There's no audiences, Could you make audience first?" %>
        </a>
      </h2>
    <% end %>
  </div>

</div>

exmail/web/templates/campaign/distribute_sent.html.eex
<div class='resources col-lg-10 col-centered'>

  <h1 class='h2 text-center'>
    <%= gettext "Send emails accomplished" %>
  </h1>

  <h2 class='h4 text-center'>
    <%= gettext "Your campaign is in the send queue and will go out shortly." %>
  </h2>

  <h2 class='h5 text-center'>
    <p>
      <%= gettext "'%{name}' will be sent to %{num} subscribers from the list, '%{type}'.",
                      name: @campaign.name, type: @campaign.type, num: length(@campaign.audience.subscribers) %>
    </p>
  </h2>

  <h2 class='h2 text-center'>
    <p>
      <%= gettext "Your campaign will send from" %><span style='display: inline-flex;' class="timer" data-seconds-left=<%= timeleft @campaign %>></span></span><%= gettext "time over" %>
      <br/>
      <%= link gettext("Cancel Send-Email"), to: campaign_path(@conn, :cancel_email, id: @campaign.id, rid: @campaign.report.id), class: "btn btn-warning", method: "delete" %>
    </p>
  </h2>

  <div class="middle text-center">
    <%= link gettext("Track performance in reports"), to: report_path(@conn, :index), class: "btn btn-default" %>
    <%= link gettext("Track performance in mobile app"), to: report_path(@conn, :index), class: "btn  btn-default disabled" %>
  </div>
</div>

exmail/web/templates/campaign/distribute_setup.html.eex
<div class='resources'>

  <h1 class='h2'>
    <%= gettext "Campaign Info" %>
  </h1>

  <%= render "form.html", Map.merge(assigns, %{
        changeset: @changeset,
        action: campaign_path(@conn, :distribute, wizard: "SaveSetup")
      })
  %>

  <%= if present?(@campaign) do
        render_with __MODULE__, "_distribute_navigation.html", assigns
      end %>

  <%#= link "Cancel", to: subscriber_path(@conn, :index) %>


</div>

exmail/web/templates/campaign/index.html.eex
<div class='resources campaign'>

  <h1 class='h2'>

    <%= gettext "Campaigns" %>

    <div class="btn-group  pull-right">
      <%= link gettext("Create Campaign"), to: campaign_path(@conn, :distribute), class: "btn btn-default" %>
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="caret"></span>
        <span class="sr-only"><%= gettext "Toggle Dropdown for Campaigns" %></span>
      </button>
      <ul class="dropdown-menu">
        <li><a href="#"><%= gettext "Regular Campaign" %></a></li>
        <li class='disabled'><a href="#"><%= gettext "Plain-Text Campaign" %></a></li>
        <li class='disabled'><a href="#"><%= gettext "A/B Testing Campaign" %></a></li>
        <li class='disabled'><a href="#"><%= gettext "Automated Campaign" %></a></li>
        <li class='disabled'><a href="#"><%= gettext "RSS Campaign" %></a></li>
      </ul>
    </div>
  </h1>

  <div class="middle state-icon">
    <%= for camp <- @campaigns do %>
      <% reltype = Campaign.reltype camp %>
      <hr class='clearfix' />

      <div class="media">
        <div class="media-body pointer" aria-controls="recipient-radio" aria-expanded="true" data-target="#recipient-radio-<%= camp.id %>" data-toggle="collapse">
          <div class="media-heading">
            <h3>
              <%= if present?(camp.report) and not cancelable?(camp) do %>
                <i class="fa fa-check-square-o fa-2x text-success" aria-hidden="true"> </i>
              <% end %>
              <%= if present?(camp.report) and cancelable?(camp) do %>
                <i class="fa fa-clock-o fa-2x text-warning" aria-hidden="true"> </i>
              <% end %>
              <%= unless present?(camp.report) do %>
                <i class="fa fa-edit fa-2x" aria-hidden="true"> </i>
              <% end %>
              <div><%= camp.name || gettext("Untitled") %></div>
            </h3>
          </div>
          <p><strong><%= camp.type %></strong>: <%= camp.audience.name %></p>
          <p>
            <%= if present?(camp.report) and not cancelable?(camp) do %>
              <strong><%= gettext "Sent" %></strong><%= gettext " on %{date} ago by %{name}", date: time_ago_in_words(camp.report.inserted_at), name: camp.user.email %>
            <% end %>
            <%= if present?(camp.report) and cancelable?(camp) do %>
              <strong><%= gettext "Scheduled" %></strong><%= gettext " at %{date}, which will send email", date: view_time(reltype.schedule) %>
            <% end %>
            <%= unless present?(camp.report) do %>
              <strong><%= gettext "Edited" %></strong><%= gettext " on %{date} ago by %{name}", date: time_ago_in_words(camp.updated_at), name: camp.user.email %>
            <% end %>
          </p>
        </div>
        <div class="media-right vmiddle"  aria-controls="recipient-radio" aria-expanded="true" data-target="#recipient-radio-<%= camp.id %>" data-toggle="collapse">
          <div class="btn-group">
            <%= if present?(camp.report) and not cancelable?(camp) do %>
              <%= link gettext("View Report"), to: report_path(@conn, :overview, camp.report), class: "btn btn-default" %>
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only"><%= gettext "Toggle Dropdown for View Report" %></span>
              </button>
              <ul class="dropdown-menu">
                <li class='disabled'><a href="#"><%= gettext "View email" %></a></li>
                <li class='disabled'><a href="#"><%= gettext "Rename" %></a></li>
                <li class='disabled'><a href="#"><%= gettext "Replaciate" %></a></li>
                <li class='disabled'><a href="#"><%= gettext "Social Share" %></a></li>
              </ul>
            <% end %>

            <%= if present?(camp.report) and cancelable?(camp) do %>
              <%= link gettext("Cancel"), to: campaign_path(@conn, :cancel_email, id: camp.id, rid: camp.report.id), class: "btn btn-default", method: "delete" %>
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only"><%= gettext "Toggle Dropdown for Campaigns" %></span>
              </button>
              <ul class="dropdown-menu">
                <li class='disabled'><a href="#"><%= gettext "Replaciate" %></a></li>
              </ul>
            <% end %>

            <%= unless present?(camp.report) do %>
              <%= link gettext("Edit"), to: distribute_path(@conn, camp, reltype, "Setup"), class: "btn btn-default" %>
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only"><%= gettext "Toggle Dropdown for Campaigns" %></span>
              </button>
              <ul class="dropdown-menu">
                <li class='disabled'><a href="#"><%= gettext "Replaciate" %></a></li>
              </ul>
            <% end %>

          </div>
        </div>
      </div>
    <% end %>

    <div class='clearfix'></div>
    <div class='wrap-pagination'>
      <% params = take_params @conn,
                              carried_params(),
                              distance: 7,
                              first: false, last: false,
                              previous: Phoenix.HTML.raw("&leftarrow;"), next: Phoenix.HTML.raw("&rightarrow;") %>

      <%= pagination_links @conn, @campaigns, to_keylist(params) %>
    </div>
    <div class='clearfix'></div>

  </div>

</div>